mautic/api-library

lib/Mautic/Auth/OAuth.php
This PR prevents PHP error with message: 
```CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set```
I got this error on my shared host.
=> Prevented PHP error

apitester/index.php, lib/Auth/OAuth.php
DELETE requests failed because the parameters were set as CURLOPT_POSTFIELDS which the oauth server rejected (related to the failed testCreateAndDelete mentioned in #3). Fixed the issue by removing the line of code that set the post fields non get/post methods (post, put and patch sets this later in the code). 
This also fixes a few quirky issues with the api tester where ending / in the URLs was inconsistent and caused problems, the endpoint typeahead not filtering (it highlighted but did not filter), and the response output did not show.
=> Fixes bad DELETE requests and some quirky issues with the api tester

.gitignore, tests/bootstrap.php
This takes the `tests/bootstrap.php` file out of the gitignore list and adds a bootstrap file.  This file checks for the existence of a `tests/local.config.php` file and that the Composer dependencies have been installed prior to executing PHPUnit and aborts the test run if either of these conditions are not met.
=> Unignore tests/bootstrap.php

tests/Api/MauticApiTestCase.php, tests/local.config.php.dist
This adds support for using the OAuth1a spec for tests. Refer to the local.config.php.dist file for the changes needed.
=> Add OAuth1a spec support to tests

apitester/endpoints/Leads.json, lib/Api/Api.php, lib/Api/Leads.php, tests/Api/LeadsTest.php
This adds support for the new endpoints /leads/{id}/lists and /leads/{id}/campaigns (companion to https://github.com/mautic/mautic/pull/246), added filtering parameters to getLeadNotes (changed from getNotes to getLeadNotes to match the two new functions), and changes the 'filter' parameter to 'search' which is what the API now accepts.
=> New lead endpoints

lib/Auth/OAuth.php
**Background**
Mautic has a PR that allows the admin to configure a consumer without restricting to a specific callback URL. In this scenario, the oauth server needs to know what URL to return to post authorization. The library didn't include the callback when requesting the token and thus Mautic didn't redirect back to the requesting script. 
**Testing**
This is in partnership with PR https://github.com/mautic/mautic/pull/358. Create an oauth1a consumer without restricting a callback. Then try to authorize via the api tester. Before the PR, the server would just download a file with the token and not redirect. After the PR, the user should be redirected back to the api tester or whatever is included as the callback.  If a callback is configured in the Consumer, using a different callback …
=> Appended the callback to the authorize URL for OAuth1a

lib/Auth/ApiAuth.php, lib/MauticApi.php
This PR creates two new factory methods to replace the existing static methods in the `ApiAuth` and `MauticApi` classes.  With the current structure, these factory methods cannot be mocked in unit testing since PHPUnit cannot mock a static method.
In the `ApiAuth` class, the old `initiate` method is proxied directly to the new `newAuth` method.  In the `MauticApi` class, the new `newApi` method is mostly a carbon copy of the `getContext` method except without the static object cache; best practices for a factory method are that it should always return a new object and not have internal storage too.
Both static methods are flagged as deprecated and may be removed at a later date.
=> Create non-static factory methods

lib/Api/Api.php
This adds support for logging the response object returned from the auth object's `makeRequest` at a debug level.
=> Log the API response at a debug level

README.md
Authorization's sample code does not working.
Because it losted ','.
```
PHP Parse error:  syntax error, unexpected ''clientKey'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' 
```
=> fix sample code error.

apitester/endpoints/Leads.json
There's no template for the leads delete action in API-tester and documentation seems to have the URL wrong - please see https://github.com/mautic/developer-documentation/issues/11 .
This pull request adds the template for leads delete URL into API-tester.
=> add leads/{id}/delete URL template into API-tester

lib/Api/Api.php
Even if the base url ends with a '/' , the setBaseUrl function was adding another '/' at the end of the Url. 
Because of this if api url was already set to _https://your_mauti_url/api/_, will end up as _https://your_mautic_url/api//_. 
Then in the second part of the function it checks if the url ends with 'api/' also fails because of the extra '/' added. This results in an api url like _https://your_mautic_url/api//api/_ which breaks all the api calls.
=> use substr instead of strpos to match url ends with /

lib/Auth/ApiAuth.php
Use the correct phpDoc `@return` statement. This is the type which is expected by the `\Mautic\MauticApi::newApi()`
=> ApiAuth::newAuth() returns a new ApiInterface

lib/Api/Api.php, lib/Api/Assets.php, lib/Api/Campaigns.php, lib/Api/Categories.php, lib/Api/Companies.php, lib/Api/Contacts.php, lib/Api/DynamicContents.php, lib/Api/Emails.php, lib/Api/Forms.php, lib/Api/Notes.php, lib/Api/Notifications.php, lib/Api/Pages.php, lib/Api/PointTriggers.php, lib/Api/Points.php, lib/Api/Reports.php, lib/Api/Roles.php, lib/Api/Smses.php, lib/Api/Stages.php, lib/Api/Users.php, tests/Api/ExceptionsTest.php, tests/Api/MauticApiTestCase.php
It can be useful to ask a API endpoint whether it supports some search command we'd like to use. One particular use case can be if we can get several items by IDs in one request or one by one; if we can use the `ids:ID1,ID2,IDn` command. Now it's possible to do something like this:
```
$ids = [243,342,34];
if ($api->hasSearchCommand('ids')) {
// Use only one API call to get all the items
$items = $api->getList('ids:'.implode(',', $ids))[$api->listName()];
} else {
// If the search command is not available, fetch them one by one
$items = [];
foreach ($ids as $id) {
$items[] = $api->get($id)[$api->itemName()];
}
}
```
Test with `$ phpunit --filter testSearchCommands`
=> Search commands

lib/Auth/OAuth.php
This PR addresses Issue #75 which is an error in the normalization of the Signing-String.
To test this PR, create a unit test to create a new contact and use the data example from the Issue to test. Without this fix, the second example will fail with a signature error. After this PR is installed the test case should now pass.
=> Bugfix for Issue #75 OAuth1 Signature error

lib/Auth/AbstractAuth.php
This PR adds the ability to set the timeout for a cURL request when using OAuth, Basic Auth or any extension of the `AbstractAuth` class
=> Have ability to set cURL timeout for requests

lib/Api/Contacts.php
Simply fixes the Owner typo in the Contacts API class
=> Fix: Onwer typo in lib/Api/Contacts.php

tests/Api/MessagesTest.php
When the channelName param was added to the marketing message response, it broke the tests. This PR unsets the channelName before it's sent to create/edit MM.
=> Fixing marketing message channels test assertion after channelName was added

tests/Api/ContactsTest.php, tests/Api/LeadsTest.php
Fixing phpunit tests for Mautic 2.8.0 together with https://github.com/mautic/mautic/pull/3881
How to test:
Apply https://github.com/mautic/mautic/pull/3881 on your Mautic, then apply this PR and run `phpunit` in the api-library directory.
=> Contact tests fixed after contacts with the same email are being merged into one

lib/Api/Api.php, lib/Api/Themes.php, lib/Auth/AbstractAuth.php, tests/Api/ThemesTest.php
This will permit to set a different path than '/tmp' to distributed environments.
How to test:
Apply this PR and run `phpunit tests/Api/ThemesTest.php` in the api-library directory.
=> Add method to set temporary filepath in theme API

tests/Api/FormsTest.php
Tests updated to test this fix: https://github.com/mautic/mautic/pull/4317
=> Test that the form fields are being created with the alias we set via API, not auto-generated

tests/Api/StatsTest.php
Support for https://github.com/mautic/mautic/pull/4419
=> plugin_citrix_events and new lead_event_log tables added to the stats API endpoint

lib/Auth/AbstractAuth.php, lib/Exception/AbstractApiException.php, lib/Exception/UnexpectedResponseFormatException.php, lib/Response.php, tests/Api/Auth/AbstractAuthTest.php, tests/ResponseTest.php
This PR moves the HTML response responsibility from `AbstractAuth` to new `Response` class. It improves testability and the tests are part of this PR.
This PR also slightly changes the behavior. I don't consider it a BC break but bug fix.
- If the response is in bad format like HTML the `UnexpectedResponseFormatException` is thrown. This exception was previously thrown only if HTTP code was not 200 or 201.
- The `UnexpectedResponseFormatException` has first new param and that is the new Response class so it could build a more detailed error message out of it. That can be considered to be BC, but exceptions from this library should not be thrown in code outside of this library.
=> Better handling of bad responses, Response class started, tests added

README.md, lib/Exception/AbstractApiException.php, lib/Response.php, tests/Api/CompanyFieldsTest.php, tests/Api/ContactFieldsTest.php, tests/Api/ContactsTest.php, tests/Api/ExceptionsTest.php, tests/Api/FormsTest.php, tests/ResponseTest.php
This PR adds HTTP code to the thrown exception and since I noticed some unit tests are failing this contains fixes of those failures as well.
Checkout your dev Mautic to use this fix: https://github.com/mautic/mautic/pull/5520
Run `vendor/bin/phpunit` and all tests should pass.
=> 404 error handling and unit test fixes

lib/Api/Contacts.php
The Problem here is that the searchstring gets repeatet.
`$contactApi->getIdentified(some@ma.il);`
will end up in a searchstring like:
`some@ma.ilsome@ma.il !is:anonymous`
This way no client is found.
=> Update for Contacts getIdentified

lib/Auth/OAuth.php
Currently oAuth authenfication for nested arrays is broken as those
information is not encoded like the server decodes the information.
This patch simplifies the normalization handling and processes
nested arrays in a proper way. Unfortunately oAuth documentation
fails to give some expectations on how to normalize nested array
information correctly.
=> Correctly normalize parameters for oAuth authentication

lib/Auth/AbstractAuth.php
In some environments & encodes to &. You already made fix in http_build_query function call for POST request, but GET request - leaved unchanged. Current issue similar to this #25.
=> Fixing ampersand encoding for GET request issue #175

lib/Api/Smses.php
In last mautic version send SMS to contact expects GET method and not POST. So the method `sendToContact` always responses with 404. Not sure if it is must be fixed in library or on Mautic side.
=> SMS send to contact GET method

lib/Auth/AbstractAuth.php, lib/Auth/OAuth.php
This edit fix the oAuth issue that raised when changed the POST to use  json_encode instead of http_build_query #216
=> Fix OAuth Authorization

README.md
This PR adds several Packagist badges to README.md, like the latest version of the API library, total downloads, etc.
You can see a preview of what it looks like at https://github.com/dennisameling/api-library/blob/add-badges-to-readme/README.md
=> Add Packagist badges to README.md

.github/workflows/tests.yml
We've had some issues with PHP sessions in the past. Check if using Redis also works, hopefully it will speed up the tests as well!
More context in https://github.com/mautic/mautic/issues/2546#issuecomment-474040841 and https://ma.ttias.be/php-session-locking-prevent-sessions-blocking-in-requests/
=> Use Redis for session storage in CI

.github/workflows/tests.yml
Closes #255 
After merging this PR, then manually kicking off the API library tests, it will be possible to specify a specific PR from `mautic/mautic` to test against 🎉 
Example run which tests against https://github.com/mautic/mautic/pull/10259: https://github.com/mautic/api-library/actions/runs/1030643520
=> Allow testing specific PR in Actions workflow

.github/workflows/tests.yml
This has been fixed upstream in the meantime: https://github.com/oerdnj/deb.sury.org/issues/1682
=> No longer need to force PHP 7.4.25 in CI

.github/workflows/tests.yml
The API tests have been running against the `features` branch all this time 🤦🏼‍♂️ let's simply test against the default branch moving forward (which is 4.x at the time of writing, but _will_ change eventually).
CI will obviously fail on this one because _lots_ of changes were introduced in Mautic in the meantime.
=> Use default `mautic/mautic` branch instead of `features`

.github/ci-files/local.config.php, .github/workflows/mautic-apache.conf, .github/workflows/tests.yml, lib/Api/Stats.php, tests/Api/MauticApiTestCase.php, tests/Api/SegmentsTest.php
addressed issues:
* Mautic was installed in a subdir, which isn't compatible with the default .htaccess, resulting in 403 errors
* the Twilio db insertion had a hardcoded id, which is not ideal if other plugins are already defined in that table
* the `stats` endpoint has a trailing slash, resulting a redirect, that the api doesn't handle correclty
* fixed the order in `assertPayloadItem` to correctly show the `Expected` and `Actual` values in failing tests
* changed segment tests to be compatible with https://github.com/mautic/mautic/pull/8649
* add workaround for batch segment tests
=> fix failing in tests

.github/workflows/tests.yml
Since https://github.com/mautic/mautic/pull/11498 was merged, the api tests seems to fail.
This is caused because Mautic is installed in the `test` env (using md5 hashing for passwords), but is consumed in the `dev` env using bcrypt.
This PR ensures Mautic is installed in dev env
=> Correct mautic env

.ddev/config.yaml, .github/workflows/tests.yml, composer.json, composer.lock, tests/Api/CompaniesTest.php, tests/Api/ContactsTest.php, tests/Api/MauticApiTestCase.php
I keep getting these daily emails that CI is failing for this repo. Here's a failing run: https://github.com/mautic/api-library/actions/runs/3922881304
Things are failing because PHP 8.0 is now required. This PR updates PHP to that version, which hopefully should fix things.
=> Use PHP 8.0 in CI due to failing runs

lib/Auth/OAuth.php
Fix for 
Deprecated
: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in api-library/lib/Auth/OAuth.php on 
- line 388
- line 395
- line 637
=> Fix - Deprecated PHP 8.1

.gitignore
When you run PHP-CS-Fixer this file is created, which should not be in VCS, so I added it to the `.gitignore`.
=> build: add .php-cs-fixer.cache to .gitignore

.ddev/mautic-local.php.dist, .ddev/mautic-setup.sh, .github/ci-files/local.php, .github/workflows/tests.yml
As the e-mail step was removed from mautic/mautic (see https://github.com/mautic/mautic/pull/12216), the tests need to be adapted in this repo, to be able to install Mautic correctly.
This PR addresses this
=> make the test flow compatible with removed email step

.github/workflows/tests.yml
see https://github.com/mautic/mautic/pull/12213#issuecomment-1512692220
this is most likely related tot the default `memory_limit` of 128M, which is not enough for the standard apache install.
This PR is a mitigation: the proper solution I'm working on is in https://github.com/mautic/api-library/pull/290
I also pushed this PR, so we can test it against the Symfony 5 PR, see the workflow: https://github.com/mautic/api-library/actions/runs/4740330977
both the workflow from this PR as the extra workflow should succeed before merging this
=> bump memory limit to ensure Mautic in dev mode can handle it

lib/Api/Api.php
Fixes https://github.com/mautic/api-library/issues/233
Ensures that the mautic-version header key is always converted to lowercase prior to checking if it exists. This makes the getMauticVersion() command less error-prone, e.g. if Nginx is used as reverse-proxy which convertes HTTP headers to lower-case.
=> Fix getMauticVersion() accessing lower-case headers as array-key

.github/ci-files/local.php
Since the recent mailer / messenger changes in Mautic, the api library tests are broken.
This PR addresses the failures, by switching the Mautic config to the new DSN style.
=> switch to dsn mailer config to ensure mail tests succeed

.github/ci-files/.env, .github/workflows/tests.yml
by using `test` env, we can use the speed optimised password hashing with md5
**before**
**after**
=> use mautic in test mode to speed up tests

composer.json
in #311 `paratest` was removed, and `phpunit` was used instead, but the composer script was not adapted.
This PR fixes this.
To test, check if `composer test` actually starts running tests (regardless if they fail or not)
=> add the correct command for the test script

tests/Api/EmailsTest.php
See the reasoning behind this change at https://github.com/mautic/mautic/pull/13697
=> An empty DEC filter shouldn't have any value. It will be null-ed in the response

lib/Api/Contacts.php, lib/Api/PointGroups.php, tests/Api/ContactsTest.php, tests/Api/PointGroupsTest.php
API library changes for https://github.com/mautic/mautic/pull/13517
=> DPMMA-2550 Point Groups API

.github/workflows/tests.yml, composer.json, lib/MauticApi.php, phpstan.neon, tests/Api/AssetsTest.php, tests/Api/CampaignsTest.php, tests/Api/FormsTest.php, tests/Api/UtmTagsTest.php
This PR supersedes an earlier attempt to integrate PHPSTAN, which encountered conflicts. The conflicts have been resolved in this updated implementation.
=> Add PHPSTAN

.github/workflows/tests.yml
At some point we should use DDEV env for running Mautic so the 2 repos are independent.
=> Run tests on PHP 8.1 as Mautci 5.2 dropps support for 8.0

.github/workflows/tests.yml
https://github.com/mautic/api-library/commit/e968a0d51e90fb3a45652831929b90bf679f1100/checks
PHPUnit tests are failing due to an unsupported MySQL version. This PR updates the MySQL version to the minimum supported version, which is 8.4.
```
Error:   - [error] Your database version (5.7.44) is too old for Mautic to work correctly. Supported versions are MySQL 8.4.0 (or higher) and MariaDB 10.11.0 (or higher).
```
=> Bump MySQL version to 8.4
