mautic/api-library

apitester/endpoints/Campaigns.json
apitester/endpoints/Emails.json
apitester/endpoints/Lists.json
apitester/index.php
lib/Mautic/Api/Campaigns.php
lib/Mautic/Api/Emails.php
lib/Mautic/Api/Lists.php
lib/Mautic/Auth/OAuth.php

This is to support the new API endpoints in https://github.com/mautic/mautic/pull/199.

API updates adding new endpoints

---

apitester/endpoints/Reports.json
apitester/index.php
lib/Api/Reports.php
tests/Api/ReportsTest.php

Companion PR to https://github.com/mautic/mautic/pull/244

Report API Support

---

README.md
apitester/index.php
lib/Auth/OAuth.php

It makes implementations easier since needed URLs are populated in the library itself.

Access and authorize token URLs populated in the API library

---

composer.json
lib/Api/Api.php

This PR adds support for the PSR-3 logging interface and enables developers to log activity in requests made via the Api classes.

Add support for a PSR-3 logger to the Api class chain

---

lib/Auth/OAuth.php

Code attribute is not used for refresh token requests fix

---

apitester/endpoints/Leads.json

According to https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Config/config.php#L74

Fixed URL for updating a lead

---

README.md

validateAccessToken() returned Exception if Authanication failed.
so, we need try - catch

add try - catch for auth sample code

---

lib/Api/Contacts.php
lib/Api/Lists.php
lib/Api/Segments.php
tests/Api/ContactsTest.php
tests/Api/LeadsTest.php
tests/Api/ListsTest.php
tests/Api/SegmentsTest.php

This PR prepares the API library for Mautic 2.0.
- Leads replaced with Contacts, but Leads kept for BC
**Not ready for merge**

Update for Mautic 2.0

---

lib/Auth/OAuth.php

https://github.com/mautic/api-library/issues/25

fix http_build_query ampersand encode for symfony 1.0.2

---

tests/Api/ContactsTest.php

Test for https://github.com/mautic/mautic/pull/2142

Added a test to check if the wrong form value returns an error

---

lib/Auth/OAuth.php

This is in combination with https://github.com/mautic/mautic/pull/2330 to address https://github.com/mautic/mautic/issues/1323

Fixed issue with encoding key and parameter to generate correct signature

---

lib/Api/Api.php

Added setBaseUrl to construct function for consistency.  Added a check in setBaseUrl to append 'api/' to end of url if not included.

Updated Base URL

---

lib/Exception/AbstractApiException.php
lib/Exception/ActionNotSupportedException.php
lib/Exception/ContextNotFoundException.php
lib/Exception/IncorrectParametersReturnedException.php
lib/Exception/RequiredParameterMissingException.php
lib/Exception/UnexpectedResponseFormatException.php
tests/Api/ExceptionsTest.php

This PR includes general updates to the Mautic API to assist in its improvement.
The changes in this PR are independent of any other PR and should just work.
The first commit contains a refactor of exception handling and adds a simple verification test - This is intended as a DRY implementation.
Note: This PR should be committed AFTER #73 which adds a new Exception class. (updated to newer version here now)
**Steps to test this PR:**
1. Save, only, the new Testcase into the tests/Api folder and run with: `phpunit tests/Api/ExceptionsTest.php` - All test should pass.
2. Apply the PR
3. Run the test again and ensure all tests still pass.

Updates from initial code review

---

lib/Auth/OAuth.php
lib/Exception/AuthorizationRequiredException.php

With this change we will be able use a try and catch block to handle the automatic redirects.

Added code to handle redirects

---

lib/Api/Campaigns.php
lib/Api/Stats.php
tests/Api/CampaignsTest.php

API library update for https://github.com/mautic/mautic/pull/3292

Get campaign contacts API endpoint added with a test

---

lib/Api/Contacts.php
lib/Auth/AuthInterface.php
lib/Auth/OAuth.php

I used [PhpStan](https://github.com/phpstan/phpstan) to check this project.
This PR fixes most problems that PhpStan detected.

Problems detected by PhpStan

---

tests/Api/ContactsTest.php

Tests to https://github.com/mautic/mautic/pull/3317

New testMergingDuplicateContacts

---

lib/Api/Tweets.php
tests/Api/StatsTest.php
tests/Api/TweetsTest.php

Adds Tweets API endpoint and tests for it. Related to https://github.com/mautic/mautic/pull/3748

Tweet API endpoint added

---

lib/Api/Themes.php
lib/Auth/AbstractAuth.php
tests/Api/FilesTest.php
tests/Api/ThemesTest.php

Support for https://github.com/mautic/mautic/pull/3810
application/zip content handled automatically

Themes API endpoint

---

lib/Api/Webhooks.php
tests/Api/MauticApiTestCase.php
tests/Api/WebhooksTest.php

API library support for https://github.com/mautic/mautic/pull/4200

Webhook API endpoints added and tested

---

tests/Api/AbstractCustomFieldsTest.php
tests/Api/FocusTest.php
tests/Api/ThemesTest.php

Some of the PHPUnit tests were failing. This PR is fixing the issues.

290 test fixes

---

tests/Api/ContactsTest.php

Just improving the unit tests with a problematic value.

Test a contact field value with ampersand

---

lib/Api/Forms.php
tests/Api/FormsTest.php

Support for https://github.com/mautic/mautic/pull/4613

From submission API endpoints implemented to the library

---

.gitignore
tests/Api/WebhooksTest.php

Added tests for https://github.com/mautic/mautic/pull/4627

Webhooks event order

---

lib/Api/Contacts.php
tests/Api/ContactsTest.php

Support for the new API endpoint https://github.com/mautic/mautic/pull/4548

get all contact events method added, tested

---

tests/Api/CompanyFieldsTest.php
tests/Api/ContactFieldsTest.php
tests/Api/MauticApiTestCase.php

Tests for https://github.com/mautic/mautic/pull/5018

Field tests controll whether the field object is correct for the endpoint

---

tests/Api/PagesTest.php

Tests for https://github.com/mautic/mautic/pull/4959

customHtml and templated are added to the pages tests

---

README.md

I deleted an old statement concerning API restriction.

Update README.md: removing old restriction hint

---

lib/Api/Contacts.php

Added default value in the parameter in dnc function

---

tests/Api/ContactsTest.php

Test contact owner as well

---

README.md

Someone has already implemented companies editing for what it seems. I did some tests here and it works, however in the documentation it informs that it has not yet been implemented

Fix text in README

---

lib/Api/Smses.php

Endpoint to https://github.com/mautic/mautic/pull/5797

Send SMS to contact API

---

tests/Api/AssetsTest.php
tests/Api/CategoriesTest.php

Tests https://github.com/mautic/mautic/pull/6318

A test for category assignment added

---

lib/Api/Reports.php
tests/Api/ReportsTest.php

This adds support for report API pagination. 
Mautic PR: https://github.com/mautic/mautic/pull/6841
Dev docs PR: https://github.com/mautic/developer-documentation/pull/111

Support and tests for report API endpoint pagination added

---

lib/Api/Segments.php

Link to PR https://github.com/mautic/mautic/pull/6570

Add route to API to add multiple contact to one segment

---

lib/Api/Campaigns.php

this is in reference to mautic core PR https://github.com/mautic/mautic/pull/6125

Add Clone a Campaign to API library

---

README.md
lib/Auth/AbstractAuth.php
tests/Api/ReportsTest.php

As mentioned in https://github.com/mautic/api-library/issues/205#issuecomment-581047337

PHPUnit fixes

---

README.md

This probably can use some better wording - calling the grammar police AKA @RCheesley for doing some checks! 😊

Add info about DDEV first-run experience to README

---

.ddev/local.config.php.dist
.github/ci-files/.env.local
.github/ci-files/local.config.php
.github/workflows/tests.yml
tests/ResponseTest.php
tests/local.config.php.dist

Remove index_dev.php

---

tests/Api/AssetsTest.php
tests/Api/FilesTest.php

changes needed after https://github.com/mautic/mautic/pull/10682 was merged

switch to the correct folder for uploads

---

lib/Api/Api.php

This PR fixes PR #315 CS issue causing the tests to fail

Use LoggerAwareTrait from Psr/Log
